services:
  backup-restore-server:
    build:
      context: backup-restore-server
      target: dev
    user: 1000:1000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./tests/assets/backup-restore-config.yaml:/opt/backup-restore/.config/backup-restore-config.yaml:ro
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: linux/amd64
    command:
      [
        "backup-restore",
        "--standalone",
      ]
    environment:
      BACKUP_RESTORE_CONFIG_PATH: /opt/backup-restore/.config/backup-restore-config.yaml
      BACKUP_RESTORE_SERVER_PORT: 8080
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: sh
    command: -c 'mkdir -p /data/backup-restore && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
